dist: trusty
language: cpp
compiler: gcc
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
install:
- sudo apt-get install -qq g++-7
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
addons:
  sonarcloud:
    organization: "marcopacini-github"
    token:
      secure: "F2uneLR5DOOoHZo+YNF0Bj39YC40AuQD5hbRmsoVLhKV5nPAiVXVLa3x2ZwMWRv+L4XfGK77eKqFU5l2Oag6ma39sI0l2Onp/8sFdLfjhgdqDlzIolX7PqSA6zYDkl2NVp8Htyiayst0CRa0Aiyha0ycqeQfAdqeYe7ymVdM0RDH7Gbq/GrV5obsdjUrqMI+JvdBC19PQI2aIUGCYt9awch4RlGPpK5Gb5be02rACWu2PrpVJFCmsOBwu6+c7/r9uv3FZL4GEZSJa3ss9lhdzrXsUNd4opxGV0Ge4LKjynZMuUh3giiZXrHWotumrOKaRzMLmISvRZ3aDASa3zZ+AQRPRHh3t2Itd0DJVVZxyhVxDcGImAlHFG9XhYnL/Bn/PGPH07zHHjUBmnT6QogmgVO+1HRFgOtf38hyI5EVnWh3Rap1AVDA+Zy9YC7zwrQKwLkn8ZyP2AF4b67OWw7k5Td/DDig47gYzuWdFM9YvRwaeLNThRxzVKDGNvQNBi9sz0ffjUdbJY53CSbQQ6KKdms2Zf4Drl9uJFz2ldBBcFzJkQ5Tdz9Q3kmgvSkbkqHl0iWP7UNJ4RvQRZz8IWNR14EoAnAM37qpLy+JlPdsL5m4JM5XwrxSmqofq7jld2GgekLGHwAg5ZRC2DrYMbrlsVGEupPHDhLeCxiVxT4JamY="
script:
  - ./configure
  - build-wrapper-linux-x86-64 --out-dir bw-output make test
  - sonar-scanner